# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNHybridNative' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNHybridNative
  #***********************************************************************#
  
  # 'node_modules'目录一般位于根目录中
  # 但是如果你的结构不同，那你就要根据实际路径修改下面的`:path`
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'Core',
  'RCTText',
  'RCTImage',
  'RCTActionSheet',
  'RCTGeolocation',
  'RCTNetwork',
  'RCTSettings',
  'RCTVibration',
  'CxxBridge', # Include this for RN >= 0.47
  'RCTWebSocket',
  'ART',
  'RCTAnimation',
  'RCTBlob',
  'RCTCameraRoll',
  'RCTPushNotification',
  'RCTLinkingIOS',
  'DevSupport'
  # 在这里继续添加你所需要的模块
  ]
  
  # 如果你的RN版本 >= 0.42.0，请加入下面这行
  pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
  # React-Native dependencies
  pod 'DoubleConversion', podspec: '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'Folly', podspec: '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  #***********************************************************************#
  

  target 'RNHybridNativeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RNHybridNativeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
